const fs = require('fs');
const path = require('path');
const dir = __dirname;

function template(title, subtitle, questions) {
  const q = JSON.stringify(questions);
  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #1a1a2e; color: #e0e0e0; min-height: 100vh; padding: 2rem 1rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { text-align: center; margin-bottom: 0.5rem; font-size: 1.8rem; color: #ffffff; }
    .subtitle { text-align: center; color: #8892b0; margin-bottom: 2rem; font-size: 1rem; }
    .progress-bar-container { background: #0d1117; border-radius: 10px; height: 14px; margin-bottom: 2rem; overflow: hidden; }
    .progress-bar { background: linear-gradient(90deg, #0d6efd, #4dabf7); height: 100%; width: 0%; border-radius: 10px; transition: width 0.4s ease; }
    .progress-text { text-align: center; color: #8892b0; margin-bottom: 1rem; font-size: 0.9rem; }
    .card { background: #16213e; border-radius: 12px; padding: 2rem; margin-bottom: 1.5rem; box-shadow: 0 4px 20px rgba(0,0,0,0.3); }
    .question-label { font-size: 0.85rem; color: #4dabf7; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 0.5rem; }
    .question-text { font-size: 1.15rem; margin-bottom: 1.2rem; line-height: 1.5; color: #ffffff; }
    pre { background: #0d1117; border: 1px solid #30363d; border-radius: 8px; padding: 1rem; margin-bottom: 1.2rem; overflow-x: auto; font-size: 0.95rem; }
    code { font-family: 'Consolas', 'Fira Code', 'Courier New', monospace; color: #c9d1d9; }
    .options { list-style: none; }
    .options li { margin-bottom: 0.5rem; }
    .options label { display: flex; align-items: center; gap: 0.75rem; padding: 0.8rem 1rem; background: #0d1117; border: 2px solid #30363d; border-radius: 8px; cursor: pointer; transition: border-color 0.2s, background 0.2s; font-size: 1rem; }
    .options label:hover { border-color: #4dabf7; background: #1c2a4a; }
    .options input[type="radio"] { accent-color: #0d6efd; width: 18px; height: 18px; flex-shrink: 0; }
    .btn { display: inline-block; padding: 0.7rem 2rem; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; transition: background 0.2s, transform 0.1s; }
    .btn-primary { background: #0d6efd; color: #fff; }
    .btn-primary:hover { background: #3b82f6; }
    .btn-primary:disabled { background: #374151; cursor: not-allowed; }
    .btn-restart { background: #238636; color: #fff; margin-top: 1rem; padding: 0.7rem 2rem; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; }
    .btn-restart:hover { background: #2ea043; }
    .feedback { margin-top: 1rem; padding: 1rem 1.2rem; border-radius: 8px; font-size: 0.95rem; line-height: 1.5; display: none; }
    .feedback.correct { background: #0f5132; border: 1px solid #198754; color: #d1fae5; display: block; }
    .feedback.wrong { background: #842029; border: 1px solid #dc3545; color: #fdd; display: block; }
    .score-card { text-align: center; padding: 3rem 2rem; }
    .score-card .score { font-size: 3rem; font-weight: 700; color: #4dabf7; margin-bottom: 0.5rem; }
    .score-card .score-label { font-size: 1.2rem; color: #8892b0; margin-bottom: 1.5rem; }
    .hidden { display: none; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <p class="subtitle">${subtitle}</p>
    <div class="progress-bar-container"><div class="progress-bar" id="progressBar"></div></div>
    <p class="progress-text" id="progressText">Question 1 / 5</p>
    <div id="quizContainer"></div>
    <div id="scoreContainer" class="card score-card hidden"></div>
  </div>
  <script>
    const questions = ${q};
    let currentQuestion = 0, score = 0, answered = false;
    function renderQuestion() { const q = questions[currentQuestion]; const total = questions.length; document.getElementById('progressBar').style.width = ((currentQuestion / total) * 100) + '%'; document.getElementById('progressText').textContent = \`Question \${currentQuestion + 1} / \${total}\`; let html = \`<div class="card"><p class="question-label">\${q.label}</p><p class="question-text">\${q.text}</p>\`; if (q.code) html += \`<pre><code>\${q.code}</code></pre>\`; html += \`<ul class="options">\`; q.options.forEach((opt, i) => { html += \`<li><label><input type="radio" name="q" value="\${i}"> \${opt}</label></li>\`; }); html += \`</ul><button class="btn btn-primary" id="validateBtn" onclick="validate()" disabled>Valider</button><div class="feedback" id="feedback"></div></div>\`; document.getElementById('quizContainer').innerHTML = html; document.querySelectorAll('input[name="q"]').forEach(r => { r.addEventListener('change', () => { document.getElementById('validateBtn').disabled = false; }); }); answered = false; }
    function validate() { if (answered) { currentQuestion++; if (currentQuestion < questions.length) renderQuestion(); else showScore(); return; } answered = true; const selected = document.querySelector('input[name="q"]:checked'); if (!selected) return; const val = parseInt(selected.value), q = questions[currentQuestion]; const fb = document.getElementById('feedback'), btn = document.getElementById('validateBtn'); document.querySelectorAll('input[name="q"]').forEach(r => r.disabled = true); if (val === q.answer) { score++; fb.className = 'feedback correct'; fb.innerHTML = \`<strong>Correct !</strong> \${q.explanation}\`; } else { fb.className = 'feedback wrong'; fb.innerHTML = \`<strong>Incorrect.</strong> \${q.explanation}\`; } btn.textContent = currentQuestion < questions.length - 1 ? 'Suivant' : 'Voir le score'; }
    function showScore() { document.getElementById('quizContainer').classList.add('hidden'); document.getElementById('progressBar').style.width = '100%'; document.getElementById('progressText').textContent = 'Termine !'; const sc = document.getElementById('scoreContainer'); sc.classList.remove('hidden'); const pct = Math.round((score / questions.length) * 100); let msg = pct === 100 ? 'Parfait !' : pct >= 60 ? 'Bien joue !' : 'Continuez a reviser !'; sc.innerHTML = \`<div class="score">\${score} / \${questions.length}</div><div class="score-label">\${msg} (\${pct}%)</div><button class="btn-restart" onclick="restart()">Recommencer</button>\`; }
    function restart() { currentQuestion = 0; score = 0; answered = false; document.getElementById('scoreContainer').classList.add('hidden'); document.getElementById('quizContainer').classList.remove('hidden'); renderQuestion(); }
    renderQuestion();
  </script>
</body>
</html>`;
}

const quizzes = [
  // Already created manually: quiz-00-01, quiz-00-02
  // Section 00 remaining
  { file: "quiz-00-03-design-patterns-essentiels.html", title: "Quiz — Design Patterns essentiels", subtitle: "Module 00 — Fondamentaux", questions: [
    { label: "Factory Pattern", text: "Quand le pattern Factory est-il justifie ?", options: ["Quand on a un seul type d'objet a creer", "Quand le type exact de l'objet n'est connu qu'a l'execution", "Quand on veut eviter les constructeurs", "Quand on veut rendre le code plus court"], answer: 1, explanation: "La Factory centralise la logique de creation quand le type est determine dynamiquement (ex: format d'export choisi par l'utilisateur). Pour un seul type, c'est de la sur-ingenierie." },
    { label: "Builder vs Constructeur", text: "A partir de combien de parametres le pattern Builder devient-il preferable a un constructeur classique ?", options: ["2 parametres", "4-5 parametres", "10 parametres", "Le nombre n'a pas d'importance"], answer: 1, explanation: "Le Builder evite les constructeurs telescopiques illisibles. A partir de 4-5 proprietes, un Builder avec chaining fluent (.from().where().limit()) est plus lisible et maintenable." },
    { label: "Singleton", text: "Pourquoi le Singleton est-il souvent considere comme un anti-pattern ?", options: ["Il consomme trop de memoire", "Il cree des dependances globales cachees et rend les tests difficiles", "Il est trop lent a instancier", "Il ne fonctionne pas en TypeScript"], answer: 1, explanation: "Le Singleton cree un couplage global, rend les tests difficiles (etat persiste entre tests) et viole DIP. Preferer l'injection de dependances avec un scope singleton gere par le conteneur IoC." },
    { label: "Observer vs Strategy", text: "Quelle est la difference fondamentale entre Observer et Strategy ?", options: ["Observer est synchrone, Strategy est asynchrone", "Observer notifie plusieurs abonnes d'un changement, Strategy rend un algorithme interchangeable", "Observer est pour le frontend, Strategy pour le backend", "Il n'y a pas de difference, ce sont des synonymes"], answer: 1, explanation: "Observer decouple emetteurs et recepteurs (1-vers-N). Strategy permet de changer un algorithme a l'execution (1-vers-1 interchangeable). Observer = notification, Strategy = selection d'algorithme." },
    { label: "State Machine", text: "Dans une State Machine editoriale, pourquoi la transition Draft vers Archived est-elle interdite ?", options: ["Parce que les transitions doivent etre alphabetiques", "Parce qu'un brouillon doit d'abord etre publie avant d'etre archive", "Parce que Archived n'est pas un etat valide", "Parce que Draft et Archived sont le meme etat"], answer: 1, explanation: "La State Machine definit des transitions explicites. Un article doit suivre le cycle Draft -> Published -> Archived. Sauter des etapes violerait les regles metier (on n'archive pas ce qui n'a jamais ete publie)." }
  ]},
  { file: "quiz-00-04-principes-clean-code.html", title: "Quiz — Principes de Clean Code", subtitle: "Module 00 — Fondamentaux", questions: [
    { label: "DRY", text: "Deux boucles de tri se ressemblent dans deux fichiers differents. Faut-il immediatement les abstraire dans une fonction commune ?", options: ["Oui, toute duplication est une violation DRY", "Non, attendre une troisieme occurrence representant la meme connaissance metier", "Oui, mais seulement si elles font plus de 10 lignes", "Non, DRY ne s'applique pas aux boucles"], answer: 1, explanation: "La regle des 'trois strikes' : deux morceaux similaires peuvent rester separes. Si un troisieme apparait et qu'ils representent la meme connaissance, alors on abstrait. L'abstraction prematuree est pire que la duplication." },
    { label: "Fail Fast", text: "Quel est l'avantage principal des guard clauses en debut de fonction ?", options: ["Elles accelerent l'execution du code", "Elles eliminent l'imbrication et detectent les erreurs immediatement", "Elles reduisent la consommation memoire", "Elles sont requises par le compilateur TypeScript"], answer: 1, explanation: "Les guard clauses valident les preconditions en premier, evitent le deep nesting (if dans if dans if), et echouent avec des messages clairs avant toute operation potentiellement dangereuse." },
    { label: "Loi de Demeter", text: "Que revele l'expression user.getAddress().getCity().getPostalCode().validate() ?", options: ["Un code bien structure avec des methodes claires", "Une violation de la Loi de Demeter — le code connait trop de structures internes", "Un pattern Builder bien applique", "Une utilisation correcte du chaining"], answer: 1, explanation: "Chaque point est une connaissance de la structure interne d'un objet. Si Address change, ce code casse. La solution : delegation — user.validatePostalCode() cache la structure interne." },
    { label: "Composition vs Heritage", text: "Pourquoi la composition est-elle preferable a l'heritage dans la majorite des cas ?", options: ["L'heritage est interdit en TypeScript", "La composition reste flexible tandis que l'heritage cree un couplage fort et permanent", "La composition est plus rapide a l'execution", "L'heritage ne supporte pas les interfaces"], answer: 1, explanation: "L'heritage cree un couplage permanent entre parent et enfants. La composition assemble des comportements via des interfaces (Formatter, Sorter, Validator) et reste flexible — on peut changer les pieces sans tout reconstruire." },
    { label: "Primitive Obsession", text: "Quel code smell est present quand on utilise des string pour email, role et tenantId sans types dedies ?", options: ["Long Method", "Feature Envy", "Primitive Obsession", "Shotgun Surgery"], answer: 2, explanation: "Primitive Obsession : utiliser des types primitifs (string, number) pour des concepts metier. Avec des Value Objects (Email, TenantId, UserRole), TypeScript detecte les inversions de parametres a la compilation." }
  ]},
  { file: "quiz-00-05-dependency-injection-ioc.html", title: "Quiz — Injection de dependances et IoC", subtitle: "Module 00 — Fondamentaux", questions: [
    { label: "IoC vs DI", text: "Quelle est la relation entre IoC (Inversion of Control) et DI (Dependency Injection) ?", options: ["Ce sont des synonymes", "IoC est le principe, DI est la technique pour l'implementer", "DI est le principe, IoC est la technique", "IoC est pour le backend, DI pour le frontend"], answer: 1, explanation: "IoC est le principe general : ce n'est pas la classe qui cree ses dependances, c'est un agent externe. DI est la technique concrete pour appliquer IoC, et l'injection par constructeur est la forme la plus claire." },
    { label: "Captive Dependency", text: "Que se passe-t-il si un Singleton injecte un service Request-scoped ?", options: ["Le service Request-scoped est cree a chaque requete normalement", "Le service Request-scoped est capture et devient un Singleton de facto — fuite de donnees possible", "Une erreur de compilation se produit", "Le Singleton devient Request-scoped"], answer: 1, explanation: "C'est une 'captive dependency' : le Request-scoped est capture pour toute la vie du Singleton. Les donnees d'un utilisateur A peuvent fuiter vers l'utilisateur B — faille de securite grave." },
    { label: "Service Locator", text: "Pourquoi le Service Locator est-il considere comme un anti-pattern par rapport a l'injection par constructeur ?", options: ["Il est plus lent a l'execution", "Les dependances sont cachees, les tests sont complexes, et le code est couple a un registre global", "Il ne fonctionne pas avec NestJS", "Il consomme plus de memoire"], answer: 1, explanation: "Avec le Service Locator, les dependances sont invisibles de l'exterieur. Pour tester, il faut configurer un registre global. L'injection par constructeur rend toutes les dependances explicites et testables." },
    { label: "Testabilite", text: "Comment DI rend-il les tests unitaires possibles sans base de donnees ?", options: ["En mockant directement la base de donnees", "En injectant un InMemoryRepository qui implemente la meme interface", "En desactivant la persistance dans le code", "En utilisant une base SQLite en memoire"], answer: 1, explanation: "Avec DI, on injecte un InMemoryRepository au lieu du PostgresRepository. Les tests s'executent en millisecondes, sans infra, et sont deterministes. C'est rendu possible par la dependance a une interface." },
    { label: "Scopes NestJS", text: "Quel scope est adapte pour un service de configuration charge une seule fois au demarrage ?", options: ["Transient — nouvelle instance a chaque injection", "Request — une instance par requete HTTP", "Singleton — une seule instance pour toute l'application", "Prototype — creation a la demande"], answer: 2, explanation: "Un service de configuration est stateless et ne change pas : Singleton est le scope ideal. Il est charge une fois et partage entre toutes les requetes. Request-scoped ou Transient gaspilleraient des ressources." }
  ]},
  { file: "quiz-00-06-raisonner-en-architecte.html", title: "Quiz — Raisonner en architecte", subtitle: "Module 00 — Fondamentaux", questions: [
    { label: "Trade-offs", text: "Selon le theoreme CAP, que doit sacrifier un systeme distribue en cas de partition reseau ?", options: ["La securite ou la performance", "La consistance ou la disponibilite", "La scalabilite ou la maintenabilite", "Le cout ou la complexite"], answer: 1, explanation: "Le theoreme CAP dit qu'en cas de partition reseau, un systeme doit choisir entre consistance (toutes les lectures voient la derniere ecriture) et disponibilite (toute requete recoit une reponse). On ne peut avoir les trois." },
    { label: "Fitness Functions", text: "Qu'est-ce qu'une fitness function en architecture ?", options: ["Un test de performance du code", "Un test automatise qui verifie qu'une caracteristique d'architecture reste respectee", "Un benchmark de la base de donnees", "Un outil de profiling memoire"], answer: 1, explanation: "Les fitness functions transforment des proprietes qualitatives (performance, couplage, securite) en assertions automatisables executees en CI. Si elles passent, l'architecture est respectee." },
    { label: "ADR", text: "Pourquoi un ADR doit-il documenter les alternatives rejetees et pas seulement la decision prise ?", options: ["Pour montrer qu'on a travaille longtemps", "Pour eviter de repeter les memes debats et comprendre le contexte de la decision", "Parce que c'est requis par la norme ISO", "Pour satisfaire le management"], answer: 1, explanation: "Sans les alternatives rejetees, un nouveau developpeur pourrait proposer une option deja evaluee et eliminee. Les ADR capturent le raisonnement complet et evitent les debats repetitifs." },
    { label: "Matrice Impact/Effort", text: "Ajouter des index sur tenant_id + status dans une base existante est un exemple de quelle categorie dans la matrice impact/effort ?", options: ["Planifier soigneusement (impact haut, effort eleve)", "Faire en premier (impact haut, effort faible)", "Eviter (impact faible, effort eleve)", "Accepter si requis (impact faible, effort faible)"], answer: 1, explanation: "Ajouter des index est un gain rapide : impact eleve sur les performances, effort faible (quelques lignes de migration SQL). C'est le type d'action a faire en premier." },
    { label: "Monolithe vs Microservices", text: "Pour une equipe de 4 developpeurs construisant un CMS, pourquoi un monolithe modulaire est-il preferable aux microservices ?", options: ["Les microservices sont toujours plus lents", "L'overhead operationnel des microservices absorbe une part significative de la productivite d'une petite equipe", "Le monolithe est plus securise", "Les microservices ne supportent pas TypeScript"], answer: 1, explanation: "Avec 4 devs, l'overhead de K8s, tracing distribue, N pipelines CI/CD et la coordination inter-services est disproportionne. Un monolithe modulaire garde les avantages de frontieres claires sans la complexite operationnelle." }
  ]},
  { file: "quiz-00-07-posture-architecte.html", title: "Quiz — La posture d'architecte", subtitle: "Module 00 — Fondamentaux", questions: [
    { label: "Niveaux de maturite", text: "Un developpeur qui propose un refactoring en code review avec un 'pourquoi' est a quel niveau de maturite architecturale ?", options: ["Niveau 1 — Executant", "Niveau 2 — Contributeur", "Niveau 3 — Concepteur", "Niveau 4 — Architecte"], answer: 1, explanation: "Le Contributeur (niveau 2) propose des ameliorations techniques, identifie la dette technique, et suggere des alternatives. Il ne se contente plus d'executer les tickets tels quels." },
    { label: "Penser en trade-offs", text: "Quelle est la reponse typique d'un architecte a 'On prend REST ou GraphQL ?' ?", options: ["GraphQL, c'est plus moderne", "REST, c'est plus simple", "Ca depend — combien de clients differents ? Quelle complexite de queries ? Quel caching requis ?", "Les deux en parallele"], answer: 2, explanation: "Un architecte pense en trade-offs : il identifie les axes de decision (nombre de clients, complexite, caching) avant de recommander. Il n'y a jamais UNE bonne solution, il y a des compromis adaptes au contexte." },
    { label: "Framework RAPID", text: "Dans le framework RAPID, qui prend la decision finale en cas de desaccord ?", options: ["R — celui qui Recommande", "A — ceux qui valident (Agree)", "D — une seule personne qui Decide", "P — ceux qui executent (Perform)"], answer: 2, explanation: "Le D (Decide) est une seule personne qui tranche en cas de desaccord. L'erreur la plus courante : tout le monde donne son avis, personne ne decide." },
    { label: "Syndrome de l'imposteur", text: "Pourquoi le syndrome de l'imposteur est-il particulierement fort en architecture logicielle ?", options: ["Parce que l'architecture est trop complexe a comprendre", "Parce que le feedback est tres retarde et la validation subjective, contrairement au code ou les tests passent ou non", "Parce que les architectes ne codent plus", "Parce qu'il faut un diplome specifique"], answer: 1, explanation: "En dev, le feedback est immediat (CI verte). En architecture, on ne sait si la decision etait bonne que 6 mois plus tard. La validation est subjective (opinions), pas objective (tests)." },
    { label: "Reversibilite des decisions", text: "Pourquoi est-il important de distinguer les decisions 'porte a sens unique' des decisions 'porte a double sens' ?", options: ["Pour impressionner en reunion", "Pour adapter le niveau d'investissement en analyse au cout de reversal de la decision", "Pour documenter plus de choses", "Pour eviter de prendre des decisions"], answer: 1, explanation: "Une decision facilement reversible (choix de lib CSS) merite moins d'analyse qu'une decision couteuse a inverser (choix de base de donnees). On investit en analyse proportionnellement au cout de reversal." }
  ]},
  { file: "quiz-00-00-pieges-frequents-archi.html", title: "Quiz — Pieges frequents en architecture", subtitle: "Architecture logicielle — Guide de survie", questions: [
    { label: "Monolithe distribue", text: "Vous avez 12 microservices qui doivent etre deployes ensemble et partagent la meme base de donnees. Quel piege avez-vous ?", options: ["Un systeme event-driven", "Un monolithe distribue — tous les inconvenients des microservices sans les avantages", "Une architecture hexagonale", "Un monolithe modulaire bien concu"], answer: 1, explanation: "Un monolithe distribue cumule la complexite reseau, l'observabilite difficile et les transactions distribuees sans beneficier de l'isolation des pannes ni du deploiement independant." },
    { label: "Cache sans invalidation", text: "Vous avez mis du cache Redis sur toutes les endpoints avec un TTL de 1h. Les utilisateurs voient des donnees perimees. Quelle est la cause ?", options: ["Redis est trop lent", "Le TTL est trop court", "Il manque une strategie d'invalidation explicite sur les mutations", "Le cache devrait etre en memoire plutot que Redis"], answer: 2, explanation: "L'invalidation de cache est un des problemes les plus difficiles en informatique. Sans invalidation explicite sur chaque mutation (publish, update, delete), le cache devient un miroir menteur." },
    { label: "JWT localStorage", text: "Pourquoi stocker un JWT dans localStorage est-il dangereux ?", options: ["LocalStorage est trop lent pour les tokens", "Un script XSS peut lire localStorage et exfiltrer le token", "Les JWT sont trop volumineux pour localStorage", "Le navigateur supprime localStorage trop souvent"], answer: 1, explanation: "localStorage est accessible depuis n'importe quel script JS, y compris ceux injectes par XSS. La solution : cookies HttpOnly + Secure + SameSite=Strict, inaccessibles au JavaScript." },
    { label: "Big Bang Rewrite", text: "Pourquoi reecrire entierement un systeme legacy 'from scratch' est-il considere comme la pire decision strategique ?", options: ["Parce que le nouveau code sera toujours plus lent", "Parce que le code legacy contient des annees de corrections de bugs et de regles implicites qu'on perd en reecrivant", "Parce que les developpeurs n'aiment pas reecrire", "Parce que le management ne l'approuvera jamais"], answer: 1, explanation: "Le code legacy, aussi laid soit-il, encode des annees de corrections et de cas limites. Le Strangler Fig Pattern permet une migration progressive sans jamais arreter de livrer." },
    { label: "DDD sur CRUD", text: "Vous avez cree des Agregats, Value Objects et Domain Events pour un simple formulaire de contact. Quel piege est-ce ?", options: ["Under-engineering", "Over-modeling CRUD — appliquer DDD la ou un simple INSERT suffit", "Architecture hexagonale mal appliquee", "Violation du principe SOLID"], answer: 1, explanation: "Le DDD est couteux et ne se justifie que pour le Core Domain ou la complexite metier est reelle. Un formulaire de contact est un INSERT INTO — pas besoin d'un Agregat ContactRequest." }
  ]},
  // Section 01 - Patterns architecturaux
  { file: "quiz-01-01-architecture-en-couches.html", title: "Quiz — Architecture en couches", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Les 4 couches", text: "Dans l'architecture en couches, quelle couche contient la logique metier pure (entites, value objects, regles) ?", options: ["Presentation Layer", "Application Layer", "Domain Layer", "Infrastructure Layer"], answer: 2, explanation: "Le Domain Layer contient la logique metier pure, independante de tout framework ou infrastructure. C'est le coeur du systeme." },
    { label: "Direction des dependances", text: "Pourquoi l'interface du Repository est-elle declaree dans le Domain plutot que dans l'Infrastructure ?", options: ["Pour des raisons de performance", "Pour appliquer le DIP : le Domain definit le contrat, l'Infrastructure s'y conforme", "Parce que l'Infrastructure n'a pas acces aux interfaces", "Par convention de nommage"], answer: 1, explanation: "Si l'interface vivait dans l'Infrastructure, le Domain en dependrait — inversant la direction autorisee. En declarant l'interface dans le Domain, on peut changer d'ORM sans toucher au metier." },
    { label: "Layering strict vs relache", text: "Quand le layering relache (une couche peut sauter des intermediaires) est-il acceptable ?", options: ["Jamais, le strict est toujours obligatoire", "Pour des CRUDs simples ou les intermediaires ne feraient que relayer sans valeur ajoutee", "Uniquement en production, pas en developpement", "Quand l'equipe est petite"], answer: 1, explanation: "Le layering relache est acceptable pour les lectures simples ou l'intermediaire ne fait que passer les donnees. Le strict convient aux domaines complexes avec des regles metier riches." },
    { label: "Anti-pattern", text: "Quel est le principal risque d'une architecture en couches mal implementee ?", options: ["Trop de fichiers dans le projet", "Le couplage inter-couches rend le refactoring aussi difficile qu'un monolithe spaghetti", "Les tests sont trop rapides", "Le deploiement est trop simple"], answer: 1, explanation: "Si les couches se connaissent intimement (imports croises, types partages), on perd tous les benefices de la separation. Le couplage inter-couches est le piege principal." },
    { label: "Quand l'utiliser", text: "Pour quel type de projet l'architecture en couches est-elle la plus adaptee ?", options: ["Un microservice avec 2 endpoints", "Une application metier classique avec des regles de gestion et du CRUD", "Un pipeline de traitement de donnees en temps reel", "Un jeu video multijoueur"], answer: 1, explanation: "L'architecture en couches est le pattern le plus repandu pour les applications metier : elle separe bien les preoccupations et reste simple a comprendre pour des equipes de taille moyenne." }
  ]},
  { file: "quiz-01-02-architecture-hexagonale.html", title: "Quiz — Architecture hexagonale", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Ports & Adapters", text: "Dans l'architecture hexagonale, quelle est la difference entre un Port Primaire et un Port Secondaire ?", options: ["Primaire = entree (le coeur est appele), Secondaire = sortie (le coeur appelle l'exterieur)", "Primaire = base de donnees, Secondaire = API", "Primaire = production, Secondaire = test", "Il n'y a pas de difference fonctionnelle"], answer: 0, explanation: "Un Port Primaire (driving) est une interface d'entree : REST, CLI appellent le coeur. Un Port Secondaire (driven) est une interface de sortie : le coeur demande a persister, envoyer un email, etc." },
    { label: "Adapter en memoire", text: "Pourquoi l'adapter 'en memoire' est-il considere comme le super-pouvoir de l'architecture hexagonale ?", options: ["Il est plus rapide que PostgreSQL", "Il permet de tester le coeur complet sans aucune infrastructure reelle", "Il reduit la consommation memoire", "Il simplifie le deploiement"], answer: 1, explanation: "Avec un InMemoryRepository, on teste Domain + Use Cases sans DB, sans reseau, en millisecondes. C'est possible uniquement parce que le coeur ne depend que d'interfaces." },
    { label: "Independance du coeur", text: "Le coeur applicatif de l'hexagone doit-il connaitre le framework HTTP utilise (Express, NestJS) ?", options: ["Oui, pour optimiser les performances", "Non, le coeur ignore tout de l'exterieur — les adapters font la traduction", "Oui, pour la serialisation des reponses", "Seulement en production"], answer: 1, explanation: "Le coeur est comme les organes internes du corps : il fonctionne selon ses propres regles. Les adapters (nerfs/recepteurs) traduisent entre le monde exterieur et le coeur." },
    { label: "Quand eviter", text: "Quand l'architecture hexagonale est-elle de la sur-ingenierie ?", options: ["Pour tout projet avec plus de 3 developpeurs", "Pour un CRUD simple sans logique metier complexe", "Pour les applications avec des tests unitaires", "Pour les projets cloud-native"], answer: 1, explanation: "L'hexagonale ajoute une complexite initiale (ports, adapters, interfaces). Pour un CRUD simple, une architecture en couches classique suffit. L'hexagonale brille quand la logique metier est riche et doit etre isolee." },
    { label: "Symetrie de l'hexagone", text: "Pourquoi l'hexagone a-t-il N faces symetriques plutot que 4 cotes comme les couches ?", options: ["Pour des raisons esthetiques", "Pour signifier que n'importe quel type de client (REST, CLI, gRPC, tests) peut se connecter via un adapter dedie", "Parce que 6 est un nombre optimal", "Pour limiter le nombre d'adapters"], answer: 1, explanation: "La symetrie signifie qu'il n'y a pas de direction privilegiee. Un adapter REST, un adapter CLI, un adapter de test — tous se connectent au coeur de la meme facon via des ports." }
  ]},
  { file: "quiz-01-03-clean-architecture.html", title: "Quiz — Clean Architecture", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Dependency Rule", text: "Quelle est la loi absolue de la Clean Architecture ?", options: ["Les couches externes doivent etre plus rapides que les internes", "Les dependances de code ne pointent que vers l'interieur — jamais l'inverse", "Chaque couche doit avoir exactement 3 classes", "Les Use Cases doivent etre stateless"], answer: 1, explanation: "La Dependency Rule dit que les couches externes (frameworks, UI, DB) dependent des couches internes (domaine, use cases). Le domaine ne sait pas qu'une base de donnees existe." },
    { label: "Entity vs Use Case", text: "Quelle est la difference entre une Entity (cercle 1) et un Use Case (cercle 2) ?", options: ["L'Entity est plus petite que le Use Case", "L'Entity contient des regles metier universelles, le Use Case contient des regles specifiques a cette application", "L'Entity est en TypeScript, le Use Case en SQL", "Il n'y a pas de difference fonctionnelle"], answer: 1, explanation: "Une Entity porte des regles qui existeraient meme sans ce logiciel (ex: facture impayee depuis 90j = contentieux). Un Use Case orchestre des regles specifiques a cette application." },
    { label: "Presenters", text: "Pourquoi la Clean Architecture introduit-elle des Presenters plutot que de laisser le Use Case retourner du JSON ?", options: ["Pour accelerer la serialisation", "Pour que le Use Case reste independant du format de sortie (JSON, HTML, CLI)", "Pour reduire la taille des reponses", "Pour satisfaire les standards REST"], answer: 1, explanation: "Si le Use Case retourne du JSON, il connait implicitement le format HTTP — violation de la Dependency Rule. Le Presenter traduit en JSON/HTML/CLI sans que le Use Case le sache." },
    { label: "Comparaison avec l'hexagonale", text: "Quelle est la principale difference entre Clean Architecture et Architecture Hexagonale ?", options: ["La Clean Architecture est plus recente", "La Clean Architecture definit des cercles concentriques avec une hierarchie stricte, l'hexagonale est symetrique", "La Clean Architecture est pour Java, l'hexagonale pour TypeScript", "Il n'y a aucune difference"], answer: 1, explanation: "L'hexagonale est symetrique (tous les adapters sont egaux). La Clean Architecture ajoute une hierarchie : Entities > Use Cases > Adapters > Frameworks. Les deux partagent le principe d'isoler le domaine." },
    { label: "Quand c'est excessif", text: "Pour quel projet la Clean Architecture complete (4 cercles) serait-elle du over-engineering ?", options: ["Un systeme bancaire avec des regles metier complexes", "Un microservice CRUD avec 3 endpoints et pas de logique metier", "Un e-commerce avec 50 000 produits", "Un CMS multi-tenant"], answer: 1, explanation: "Pour un microservice CRUD trivial, les 4 cercles ajoutent des couches d'indirection sans valeur. La complexite de l'architecture doit etre proportionnelle a la complexite du domaine." }
  ]},
  { file: "quiz-01-04-monolithe-modulaire.html", title: "Quiz — Monolithe modulaire", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Definition", text: "Qu'est-ce qui distingue un monolithe modulaire d'un 'Big Ball of Mud' ?", options: ["Le monolithe modulaire utilise des microservices", "Les modules ont des frontieres claires et communiquent par API publique, pas par acces direct aux classes internes", "Le Big Ball of Mud est plus rapide", "Il n'y a pas de difference technique"], answer: 1, explanation: "Un monolithe modulaire est un seul deployable ou les modules sont independants avec des frontieres respectees. Le Big Ball of Mud est un loft sans murs — tout le monde se croise." },
    { label: "Barrel file", text: "Quel est le role d'un barrel file (index.ts) dans un monolithe modulaire ?", options: ["Exporter toutes les classes du module sans restriction", "Re-exporter uniquement l'API publique du module et cacher les details internes", "Generer automatiquement la documentation", "Compiler le module en un seul fichier"], answer: 1, explanation: "Le barrel file est le gardien du module : il n'exporte que les classes et interfaces publiques. Les autres modules ne peuvent importer que depuis ce fichier, materialisant les frontieres." },
    { label: "Avantage cle", text: "Pourquoi un monolithe modulaire est-il souvent preferable aux microservices pour une equipe de moins de 15 developpeurs ?", options: ["Il est plus securise", "Il evite l'overhead operationnel (K8s, tracing, N pipelines) tout en gardant des frontieres claires entre modules", "Il consomme moins de memoire", "Il est plus facile a deployer sur AWS"], answer: 1, explanation: "Les appels inter-modules sont locaux (<1ms vs 5-50ms reseau), les transactions ACID sont natives, et le refactoring des frontieres est moins couteux que de deplacer du code entre services." },
    { label: "API-First", text: "Que signifie le principe API-First dans le contexte d'un monolithe modulaire ?", options: ["Tout doit passer par des API REST", "Le contrat (API) est defini avant l'implementation, permettant un decouplage entre modules", "L'API est plus importante que le code", "On developpe l'API avant le frontend"], answer: 1, explanation: "API-First signifie definir le contrat avant le code. Les modules communiquent par des interfaces explicites (contrats), pas par des imports internes. Cela prepare aussi une eventuelle extraction en service." },
    { label: "Migration future", text: "Comment un monolithe modulaire facilite-t-il une future migration vers des microservices ?", options: ["Il genere automatiquement les microservices", "Les frontieres de modules correspondent aux futurs services — on extrait un module avec son API deja definie", "Il n'y a aucun lien entre les deux", "Les microservices sont toujours meilleurs"], answer: 1, explanation: "Si les modules ont des frontieres claires et communiquent par API, extraire un module en service autonome est naturel. C'est la strategie 'monolithe d'abord, microservices si necessaire'." }
  ]},
  { file: "quiz-01-05-microservices.html", title: "Quiz — Microservices", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Data per Service", text: "Pourquoi chaque microservice doit-il posseder sa propre base de donnees ?", options: ["Pour des raisons de performance", "Pour eliminer le couplage au schema — un changement de colonne ne doit pas forcer le deploiement de 6 services", "Pour utiliser plus de serveurs", "Par convention Kubernetes"], answer: 1, explanation: "Le partage de base de donnees cree un couplage au schema : modifier une table force tous les services consommateurs a se mettre a jour simultanement, detruisant l'independance de deploiement." },
    { label: "Decomposition", text: "Pourquoi decomposer par couche technique (un service API, un service logique, un service data) est-il un anti-pattern ?", options: ["Parce que les couches sont trop petites", "Parce que cela cree un monolithe distribue — tout change ensemble", "Parce que c'est trop rapide a implementer", "Parce que les couches ne communiquent pas"], answer: 1, explanation: "La decomposition technique donne 3 services qui doivent etre deployes ensemble pour chaque feature — un monolithe distribue. La decomposition par domaine (Bounded Context) isole les features." },
    { label: "Quand adopter", text: "Quel est le signal le plus fiable qu'une equipe a besoin de microservices ?", options: ["Le CTO le recommande", "Des equipes independantes ont besoin de deployer a des rythmes differents sans se bloquer", "Le monolithe est lent", "On veut utiliser Kubernetes"], answer: 1, explanation: "Le besoin de deploiement independant par equipe/domaine est le signal le plus fort. Si toutes les features sont deployees ensemble par la meme equipe, les microservices n'apportent que de l'overhead." },
    { label: "Anti-pattern", text: "Qu'est-ce qu'un monolithe distribue ?", options: ["Un monolithe deploye sur plusieurs serveurs", "Des microservices couples qui doivent etre deployes ensemble, avec la complexite distribuee sans les avantages", "Un monolithe avec une base distribuee", "Un systeme event-driven"], answer: 1, explanation: "Le monolithe distribue combine tous les inconvenients des microservices (complexite reseau, observabilite, transactions distribuees) sans aucun de leurs avantages (isolation, deploiement independant)." },
    { label: "Communication", text: "Pourquoi la communication asynchrone (events/messaging) est-elle preferable a la communication synchrone (HTTP) entre microservices ?", options: ["Elle est toujours plus rapide", "Elle decouple les services dans le temps — si un service est down, le message attend dans la queue", "Elle est plus facile a implementer", "Elle ne necessite pas de reseau"], answer: 1, explanation: "La communication asynchrone via messaging (Kafka, RabbitMQ) offre un decouplage temporel et une resilience aux pannes. En synchrone, si le service appele est down, l'appelant echoue aussi." }
  ]},
  { file: "quiz-01-06-vertical-slice.html", title: "Quiz — Vertical Slice Architecture", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Slice vs Couche", text: "Quelle est la difference fondamentale entre une architecture en couches et une Vertical Slice ?", options: ["Les couches sont horizontales (par role technique), les slices sont verticales (par feature complete)", "Les slices sont plus rapides", "Les couches utilisent TypeScript, les slices utilisent JavaScript", "Il n'y a pas de difference structurelle"], answer: 0, explanation: "En couches : tout les controllers ensemble, tout les services ensemble. En slices : chaque feature (Creer Commande, Lister Commandes) contient son handler, sa validation, son acces aux donnees." },
    { label: "CQRS-lite", text: "Pourquoi une Query slice peut-elle utiliser du SQL direct sans passer par les Entities Domain ?", options: ["Pour des raisons de securite", "Parce que les queries ne font que lire sans appliquer de regles metier — pas besoin des Entities", "Parce que SQL est plus facile que TypeScript", "Pour contourner l'ORM"], answer: 1, explanation: "Les queries lisent des donnees pour les afficher — aucune regle metier a proteger. Un SQL optimise retournant exactement le shape necessaire est plus performant et plus simple que la reconstitution d'Entities." },
    { label: "Mediator", text: "Quel est le role du pattern Mediator dans la Vertical Slice Architecture ?", options: ["Il remplace le routeur HTTP", "Il dispatche les Commands/Queries vers les Handlers et permet d'ajouter des comportements transversaux (logging, validation)", "Il gere la base de donnees", "Il compile les slices en un seul fichier"], answer: 1, explanation: "Le Mediator decouple les Controllers des Handlers. Le Controller envoie un message, le Mediator le route. On peut ajouter logging, tracing, retry en decorant le Mediator sans toucher aux Handlers." },
    { label: "Autonomie d'equipe", text: "Comment la Vertical Slice Architecture facilite-t-elle le travail en equipe ?", options: ["Chaque developpeur a son propre serveur", "Deux developpeurs peuvent travailler sur deux features sans conflit car chaque slice est independante", "Les slices sont automatiquement distribuees", "Elle elimine le besoin de code review"], answer: 1, explanation: "Puisque chaque slice est un dossier autonome (handler + validation + repo + DTO), deux devs travaillant sur deux features ne touchent pas aux memes fichiers — zero conflit de merge." },
    { label: "Quand l'utiliser", text: "La Vertical Slice Architecture est particulierement adaptee pour quel type de projet ?", options: ["Un projet avec 2 endpoints et pas de logique metier", "Un projet avec de nombreux cas d'utilisation distincts et une equipe qui doit livrer des features en parallele", "Un script de migration de donnees", "Un site statique"], answer: 1, explanation: "Les slices brillent quand il y a beaucoup de features distinctes et une equipe qui doit livrer en parallele. Chaque slice peut etre developpee, testee et deployee independamment." }
  ]},
  { file: "quiz-01-07-twelve-factor-idempotency.html", title: "Quiz — 12-Factor App et Idempotence", subtitle: "Module 01 — Patterns architecturaux", questions: [
    { label: "Config", text: "Selon les 12-Factor, ou doit etre stockee la configuration (URLs de BDD, cles API) ?", options: ["Dans un fichier config.json dans le repo", "Dans des variables d'environnement, jamais dans le code source", "Dans la base de donnees", "Dans un fichier .env commite dans git"], answer: 1, explanation: "Le facteur III (Config) exige que la configuration soit dans l'environnement. Le meme binaire peut etre deploye dans dev, staging et prod avec des variables differentes." },
    { label: "Stateless", text: "Pourquoi le facteur VI (Processes) exige-t-il que l'application soit sans etat ?", options: ["Pour reduire la consommation memoire", "Pour rendre le scaling horizontal trivial — on peut ajouter/retirer des instances sans perdre de donnees", "Pour simplifier le code", "Pour eviter les bugs de concurrence"], answer: 1, explanation: "Si l'etat est en memoire (sessions, cache local), on ne peut pas ajouter d'instance sans perdre cet etat. L'etat doit etre externalise (Redis, BDD) pour un scale horizontal transparent." },
    { label: "Idempotence", text: "Un utilisateur clique 3 fois sur 'Payer 100 EUR' a cause d'un reseau lent. Sans idempotence, que se passe-t-il ?", options: ["Rien, le navigateur deduplique automatiquement", "300 EUR sont debites — chaque clic cree une transaction independante", "Le paiement est refuse apres le premier clic", "Le serveur detecte automatiquement les doublons"], answer: 1, explanation: "Sans idempotence, chaque requete est traitee independamment. La solution : une cle d'idempotence unique par operation. Le serveur reconnait les doublons et retourne le resultat cache." },
    { label: "Cle d'idempotence", text: "Comment fonctionne une cle d'idempotence pour eviter les doubles debits ?", options: ["Le serveur bloque toutes les requetes apres la premiere", "Le client envoie une cle unique (UUID) par operation, le serveur stocke la cle et rejette les doublons", "Le navigateur desactive le bouton automatiquement", "La base de donnees empeche les doublons via un unique constraint"], answer: 1, explanation: "Le client genere un UUID par operation (ex: paiement). Le serveur stocke cette cle apres traitement. Si la meme cle arrive a nouveau, il retourne le resultat deja stocke sans re-executer." },
    { label: "Dev/Prod Parity", text: "Pourquoi le facteur X (Dev/Prod Parity) insiste-t-il sur des environnements identiques ?", options: ["Pour utiliser les memes credentials", "Pour que les bugs detectes en dev/staging soient les memes qu'en production — pas de 'ca marche en local'", "Pour reduire les couts de serveurs", "Pour simplifier la documentation"], answer: 1, explanation: "Des environnements differents (SQLite en dev, PostgreSQL en prod) masquent des bugs qui n'apparaissent qu'en production. L'identite des environnements garantit que staging predit la production." }
  ]},
  // Section 02 - DDD
  { file: "quiz-02-01-introduction-ddd.html", title: "Quiz — Introduction au DDD", subtitle: "Module 02 — Domain-Driven Design", questions: [
    { label: "Langage Ubiquitaire", text: "Qu'est-ce que le Langage Ubiquitaire en DDD ?", options: ["Un langage de programmation universel", "Un vocabulaire partage entre developpeurs et experts metier, utilise dans le code, les reunions et la documentation", "Un framework de traduction automatique", "Le langage de la base de donnees"], answer: 1, explanation: "Le Langage Ubiquitaire elimine la traduction permanente entre vocabulaire metier et technique. Un concept ('commande annulee') a le meme nom dans la bouche du PO, du dev et dans le code." },
    { label: "Strategique vs Tactique", text: "Quelle est la difference entre DDD Strategique et DDD Tactique ?", options: ["Strategique = long terme, Tactique = court terme", "Strategique = quoi construire (Bounded Contexts, Context Map), Tactique = comment le modeliser (Entities, VO, Agregats)", "Strategique = backend, Tactique = frontend", "Il n'y a pas de difference"], answer: 1, explanation: "Le DDD Strategique definit les frontieres (Bounded Contexts) et les relations (Context Map). Le Tactique fournit les briques (Entities, Value Objects, Agregats). Sans strategique, le tactique est applique au mauvais endroit." },
    { label: "Quand utiliser le DDD", text: "Pour quel type de sous-domaine le DDD Tactique (Entities, Agregats, Events) est-il justifie ?", options: ["Tous les sous-domaines sans exception", "Uniquement le Core Domain ou la complexite metier est reelle", "Uniquement les sous-domaines generiques (auth, email)", "Uniquement les CRUDs simples"], answer: 1, explanation: "Le DDD Tactique est couteux. Il n'a de valeur que pour le Core Domain (la ou la complexite metier justifie l'investissement). Les supporting/generic subdomains meritent du CRUD simple." },
    { label: "Event Storming", text: "Quel est l'objectif principal d'un Event Storming ?", options: ["Ecrire du code en groupe", "Decouvrir les evenements metier, les commandes et les frontieres de contexte avec les experts domaine", "Tester les performances du systeme", "Planifier les sprints agiles"], answer: 1, explanation: "L'Event Storming est un atelier collaboratif ou developpeurs et experts metier placent les evenements sur un mur, revelant les flux metier et les frontieres naturelles entre contextes." },
    { label: "Piege courant", text: "Quel est le piege le plus courant quand on commence le DDD ?", options: ["Ne pas utiliser assez de patterns", "Appliquer le DDD Tactique sans avoir fait le DDD Strategique — on modelise au mauvais endroit", "Utiliser TypeScript au lieu de Java", "Ne pas avoir assez de classes"], answer: 1, explanation: "Beaucoup d'equipes creent des Agregats et Value Objects partout sans avoir identifie les Bounded Contexts. Le resultat : de la complexite la ou un simple CRUD suffisait." }
  ]},
  { file: "quiz-02-02-bounded-contexts.html", title: "Quiz — Bounded Contexts et Context Map", subtitle: "Module 02 — Domain-Driven Design", questions: [
    { label: "Definition", text: "Qu'est-ce qu'un Bounded Context en DDD ?", options: ["Un microservice", "Une frontiere explicite a l'interieur de laquelle un modele de domaine a un sens precis et coherent", "Une base de donnees separee", "Un module npm"], answer: 1, explanation: "Un Bounded Context est un pays avec son propre vocabulaire et ses propres regles. En dehors de cette frontiere, le meme terme peut avoir un sens different (ex: 'Produit' dans Catalogue vs Commande)." },
    { label: "Meme terme, sens different", text: "Pourquoi 'Produit' a-t-il un sens different dans le contexte Catalogue et dans le contexte Commande ?", options: ["C'est une erreur de conception", "Dans Catalogue c'est un objet riche (images, SEO, variantes), dans Commande c'est un snapshot fige (prix au moment de l'achat)", "Ils devraient utiliser la meme entite", "Les contextes sont mal definis"], answer: 1, explanation: "Chaque contexte a son propre modele. Forcer un modele universel 'Produit' qui satisfait les deux contextes donnerait un objet impossible a maintenir avec des dizaines de champs optionnels." },
    { label: "Anti-Corruption Layer", text: "Quand utilise-t-on une Anti-Corruption Layer (ACL) ?", options: ["Pour chiffrer les donnees", "Pour isoler son domaine d'un modele externe chaotique en traduisant les donnees a la frontiere", "Pour compresser les reponses API", "Pour valider les formulaires"], answer: 1, explanation: "L'ACL convertit le vocabulaire et la structure d'un systeme externe (API tierce, legacy) vers votre modele interne. Ex: traduire un webhook Stripe en PaymentConfirmed de votre domaine." },
    { label: "Context Map", text: "A quoi sert une Context Map ?", options: ["A documenter le code source", "A cartographier les relations entre Bounded Contexts : qui fournit quoi a qui et comment les donnees traversent les frontieres", "A mesurer la performance des services", "A planifier les sprints"], answer: 1, explanation: "La Context Map est la carte des 'traites entre pays'. Elle montre les relations (Customer/Supplier, Conformist, ACL, Shared Kernel) et comment les contextes communiquent." },
    { label: "Partage d'entites", text: "Pourquoi un Bounded Context ne doit-il pas partager ses entites avec un autre contexte ?", options: ["Pour des raisons de performance", "Parce que cela cree un couplage fort : un changement de schema dans A force une modification dans B", "Parce que TypeScript ne le permet pas", "Pour economiser de la memoire"], answer: 1, explanation: "Partager des entites cree un couplage entre equipes. La solution : chaque contexte a son propre modele, et les contextes communiquent par IDs et evenements." }
  ]},
  { file: "quiz-02-03-entites-vo-agregats.html", title: "Quiz — Entites, Value Objects et Agregats", subtitle: "Module 02 — Domain-Driven Design", questions: [
    { label: "Entity vs Value Object", text: "Quelle est la difference fondamentale entre une Entite et un Value Object ?", options: ["L'Entite est plus grosse", "L'Entite est definie par son identite (elle persiste malgre les changements), le VO est defini par sa valeur (deux VO identiques sont interchangeables)", "Le VO est stocke en base, l'Entite non", "Il n'y a pas de difference en TypeScript"], answer: 1, explanation: "Marie Dupont qui change de nom reste la meme personne (Entite avec ID). Deux billets de 20 EUR sont interchangeables — seule la valeur compte (Value Object). Les VO sont immuables." },
    { label: "Agregat", text: "Quel est le role de la Racine d'Agregat ?", options: ["Etre la plus grande classe du projet", "Etre le seul point d'entree pour modifier les entites de l'agregat, garantissant la coherence des invariants metier", "Generer les IDs", "Gerer la connexion a la base de donnees"], answer: 1, explanation: "Toutes les modifications passent par la Racine d'Agregat, comme adopter un enfant passe par les parents (la Racine). Cela garantit que les invariants metier sont toujours respectes." },
    { label: "UUID v4", text: "Pourquoi utilise-t-on des UUID v4 plutot que des IDs sequentiels (1, 2, 3) ?", options: ["Les UUID sont plus courts", "Les IDs sequentiels permettent l'enumeration (attaque IDOR), les UUID rendent la prediction impossible", "Les UUID sont plus rapides en base", "Par convention DDD"], answer: 1, explanation: "Avec des IDs sequentiels, un attaquant peut tester /articles/43 apres /articles/42. Les UUID v4 ont 2^122 possibilites, rendant l'enumeration impossible et permettant la generation cote client." },
    { label: "Immuabilite du VO", text: "Pourquoi les Value Objects doivent-ils etre immuables ?", options: ["Pour economiser de la memoire", "Parce qu'un changement de valeur cree un nouveau VO — modifier un billet de 20 EUR ne donne pas un billet de 50 EUR", "Pour simplifier le garbage collector", "Par convention TypeScript"], answer: 1, explanation: "Un VO est defini par sa valeur. Si on change la valeur, c'est un AUTRE VO. L'immuabilite evite les effets de bord : un Money(20) reste toujours Money(20), on cree un nouveau Money(50) si besoin." },
    { label: "Optimistic Locking", text: "Comment l'optimistic locking detecte-t-il les conflits d'edition simultanee ?", options: ["En verrouillant la ligne en base de donnees", "En comparant un champ version : si la version lue differe de la version actuelle, on rejette avec une erreur", "En utilisant des timestamps", "En bloquant les autres utilisateurs"], answer: 1, explanation: "Chaque entite porte un champ version incremente a chaque modification. Lors de la sauvegarde, WHERE id = ? AND version = ? detecte si quelqu'un a modifie entre temps. Pas de verrou, pas de blocage." }
  ]},
  { file: "quiz-02-04-domain-events-services.html", title: "Quiz — Domain Events et Services", subtitle: "Module 02 — Domain-Driven Design", questions: [
    { label: "Domain Event", text: "Comment doit etre nomme un Domain Event et pourquoi ?", options: ["Au futur (WillPublishArticle) car il anticipe une action", "Au passe (ArticlePublished) car il represente un fait accompli et immuable", "A l'imperatif (PublishArticle) car c'est une commande", "Au present (PublishingArticle) car c'est en cours"], answer: 1, explanation: "Un Domain Event constate un fait accompli, irreversible. ArticlePublished (passe) est un fait. PublishArticle (imperatif) serait une commande, pas un evenement." },
    { label: "Domain Service vs Application Service", text: "Quelle est la difference entre un Domain Service et un Application Service ?", options: ["Il n'y a pas de difference", "Le Domain Service porte de la logique metier pure (sans infra), l'Application Service orchestre le flux (charge, invoque, sauvegarde, publie)", "Le Domain Service gere la base de donnees", "L'Application Service contient les regles metier"], answer: 1, explanation: "Un Domain Service (ex: PricingService) applique des regles metier impliquant plusieurs agregats. Un Application Service orchestre : charge via Repository, invoque le domaine, sauvegarde, publie les events." },
    { label: "Compensation", text: "Pourquoi dit-on qu'un Domain Event ne peut pas etre annule ?", options: ["Pour des raisons techniques", "Parce que c'est un fait passe immuable — on compense avec un nouvel evenement (OrderCancelled apres OrderPlaced)", "Parce que la base de donnees ne le permet pas", "Par convention DDD"], answer: 1, explanation: "Un evenement est un fait historique : on ne peut pas 'de-publier' un article dans l'historique. On ajoute un nouvel evenement ArticleUnpublished. C'est le principe de l'append-only." },
    { label: "FSM", text: "Quel avantage une machine a etats finis (FSM) apporte-t-elle par rapport a des if/else pour gerer les transitions de statut ?", options: ["Elle est plus rapide", "Les transitions valides sont declarees explicitement, les invalides levent une exception — c'est exhaustif, lisible et testable", "Elle consomme moins de memoire", "Elle genere automatiquement les tests"], answer: 1, explanation: "Avec une FSM, toutes les transitions sont centralisees et verificables. Ajouter un etat se fait en un seul endroit. Les if/else dispersent la logique et les cas invalides passent silencieusement." },
    { label: "Audit trail", text: "Pourquoi un audit trail doit-il etre append-only ?", options: ["Pour economiser de l'espace disque", "Pour garantir qu'aucune entree ne peut etre modifiee ou supprimee apres coup — integrite de l'historique", "Pour accelerer les lectures", "Pour simplifier les requetes SQL"], answer: 1, explanation: "Un audit trail append-only garantit l'integrite : chaque action est enregistree de facon immuable. Meme un admin ne peut pas effacer ses traces. C'est essentiel pour la conformite et la tracabilite." }
  ]},
  { file: "quiz-02-05-repositories-specifications.html", title: "Quiz — Repositories et Specifications", subtitle: "Module 02 — Domain-Driven Design", questions: [
    { label: "Repository vs DAO", text: "Quelle est la difference entre un Repository et un DAO ?", options: ["Ce sont des synonymes", "Le Repository travaille au niveau de l'Agregat metier avec des methodes orientees domaine, le DAO est oriente infrastructure avec des methodes SQL", "Le DAO est plus recent", "Le Repository est pour NoSQL, le DAO pour SQL"], answer: 1, explanation: "Le Repository (findPublishedByTenant) est defini dans le domaine et ne connait pas la DB. Le DAO (findByColumn, insert) reflete les operations SQL. Le Repository respecte la Dependency Rule." },
    { label: "Specification Pattern", text: "Comment le Specification Pattern resout-il l'explosion combinatoire des methodes de recherche ?", options: ["En creant une methode par combinaison", "En encapsulant chaque critere dans un objet composable via and(), or(), not()", "En utilisant du SQL dynamique", "En cachant tous les resultats"], answer: 1, explanation: "Au lieu de findByStatusAndTag, findByStatusAndAuthor, etc., chaque critere est un objet independant (PublishedSpec, HasTagSpec). On les compose : PublishedSpec.and(HasTagSpec). La croissance est lineaire, pas exponentielle." },
    { label: "Interface dans le domaine", text: "Pourquoi l'interface ArticleRepository est-elle declaree dans le domaine et non dans l'infrastructure ?", options: ["Pour des raisons de convention", "Pour que le domaine reste independant de l'infrastructure — c'est le domaine qui definit ses besoins", "Parce que l'infrastructure ne supporte pas les interfaces", "Pour eviter les imports circulaires"], answer: 1, explanation: "Le domaine definit le contrat qu'il attend (interface). L'infrastructure fournit l'implementation (PostgresArticleRepository). Si on change de DB, seule l'implementation change, pas le domaine." },
    { label: "InMemoryRepository", text: "Quel est l'interet principal d'un InMemoryRepository dans les tests ?", options: ["Il est plus proche de la production", "Il permet de tester le domaine complet sans base de donnees, en millisecondes, de facon deterministe", "Il consomme moins de memoire", "Il genere automatiquement les donnees de test"], answer: 1, explanation: "L'InMemoryRepository implemente la meme interface que le PostgresRepository. Les tests du domaine s'executent sans infra, rapidement et de facon reproductible. C'est le super-pouvoir de DI + interfaces." },
    { label: "Active Record vs Data Mapper", text: "Pourquoi le Data Mapper est-il preferable a l'Active Record pour un projet DDD ?", options: ["Il est plus rapide", "L'entite est un objet pur sans reference a la DB, donc testable et portable — pas de couplage a l'ORM", "Il genere moins de SQL", "Il est plus recent"], answer: 1, explanation: "Avec Active Record, l'entite herite d'un modele et sait se persister (product.save()). Avec Data Mapper, l'entite est pure. Un mapper separe traduit entre entite et persistance — le domaine reste isole." }
  ]},
  // Section 03 - Architecture Backend
  { file: "quiz-03-01-api-design-rest.html", title: "Quiz — API Design REST", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Conventions REST", text: "Quelle methode HTTP et quel code de reponse utiliser pour creer une nouvelle ressource ?", options: ["GET 200", "POST 201", "PUT 200", "PATCH 204"], answer: 1, explanation: "POST pour creer, 201 Created pour confirmer la creation. GET est pour lire, PUT pour remplacer, PATCH pour modifier partiellement." },
    { label: "ETag/If-Match", text: "Comment le mecanisme ETag/If-Match empeche-t-il les conflits d'edition ?", options: ["En verrouillant la ressource pour tous les autres utilisateurs", "Le serveur compare la version envoyee par le client avec la version actuelle — si differente, 412 Precondition Failed", "En serialisant toutes les requetes", "En utilisant des transactions distribuees"], answer: 1, explanation: "Le serveur envoie un ETag (version). Le client renvoie cette valeur dans If-Match lors d'une modification. Si la version a change entre temps (autre utilisateur), le serveur rejette avec 412." },
    { label: "RFC 7807", text: "Quel est l'avantage du format RFC 7807 Problem Details pour les erreurs API ?", options: ["Il est plus compact que JSON", "Il standardise la structure des erreurs (type, title, status, detail) pour tous les clients", "Il est obligatoire pour les API REST", "Il chiffre les messages d'erreur"], answer: 1, explanation: "RFC 7807 definit un format standard avec type (URI), title (description), status (code HTTP), detail (message specifique). Tous les clients savent parser la meme structure d'erreur." },
    { label: "Presigned URL", text: "Pourquoi utiliser des presigned URLs S3 pour l'upload de fichiers plutot que de faire transiter le fichier par l'API ?", options: ["S3 est plus rapide que l'API", "Le serveur API ne recoit jamais le fichier binaire — le client uploade directement vers S3, reduisant la charge serveur", "Les presigned URLs sont plus securisees", "C'est la seule methode supportee par S3"], answer: 1, explanation: "Le flux : le client demande une URL presignee, puis uploade directement vers S3. Le serveur API genere l'URL et verifie l'upload ensuite, sans jamais recevoir le fichier binaire." },
    { label: "Pagination", text: "Pourquoi imposer un cap (maximum) sur le parametre de pagination limit est-il important ?", options: ["Pour des raisons esthetiques", "Pour empecher un client de demander 1 million de resultats et surcharger la base de donnees", "Pour respecter les standards REST", "Pour simplifier le frontend"], answer: 1, explanation: "Sans cap, un client peut demander limit=1000000 et mettre la DB a genoux. Un cap raisonnable (ex: max 100) protege l'infrastructure tout en offrant de la flexibilite au client." }
  ]},
  { file: "quiz-03-02-middleware-pipeline.html", title: "Quiz — Middleware et Pipeline", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Ordre NestJS", text: "Dans quel ordre s'executent les composants du pipeline NestJS ?", options: ["Handler -> Guard -> Pipe -> Interceptor -> Middleware", "Middleware -> Guard -> Interceptor (avant) -> Pipe -> Handler -> Interceptor (apres) -> Exception Filter", "Guard -> Middleware -> Handler -> Pipe", "Pipe -> Guard -> Handler -> Middleware"], answer: 1, explanation: "L'ordre est : Middleware (Express) -> Guards (auth) -> Interceptors avant -> Pipes (validation) -> Handler -> Interceptors apres -> Exception Filters. Chaque etape peut court-circuiter les suivantes." },
    { label: "Guard vs Interceptor", text: "Quelle est la difference fonctionnelle entre un Guard et un Interceptor ?", options: ["Le Guard est plus rapide", "Le Guard prend une decision binaire (oui/non), l'Interceptor wrappe le handler et peut agir avant ET apres l'execution", "L'Interceptor est pour l'authentification", "Il n'y a pas de difference"], answer: 1, explanation: "Le Guard retourne true/false (autoriser ou rejeter). L'Interceptor wrappe le handler via un Observable : il peut mesurer le temps, transformer la reponse, ajouter du cache — avant et apres le handler." },
    { label: "Court-circuit", text: "Que se passe-t-il si un Guard retourne false dans le pipeline NestJS ?", options: ["Le handler s'execute quand meme", "Les Pipes et le Handler ne sont jamais executes — le pipeline est court-circuite", "Le Guard est ignore", "Une exception est retentee 3 fois"], answer: 1, explanation: "Si un Guard rejette (retourne false), les etapes suivantes (Pipes, Handler, Interceptors) ne sont jamais atteintes. Le pipeline repond directement avec 403/401." },
    { label: "Analogie", text: "La chaine de montage automobile est une analogie du pipeline NestJS. Que represente chaque station ?", options: ["Un microservice independant", "Une etape du pipeline (middleware, guard, interceptor, pipe, handler) avec une responsabilite unique", "Un serveur dans le cluster", "Un fichier TypeScript"], answer: 1, explanation: "Comme chaque station de l'usine (controle qualite, soudure, peinture), chaque etape du pipeline a une responsabilite unique et peut rejeter la requete sans que les etapes suivantes soient sollicitees." },
    { label: "Exception Filter", text: "A quel moment du pipeline les Exception Filters interviennent-ils ?", options: ["Avant le Guard", "En tout dernier — ils attrapent les exceptions levees par n'importe quelle etape precedente", "Entre le Middleware et le Guard", "Seulement pendant le Handler"], answer: 1, explanation: "Les Exception Filters sont le filet de securite final. Qu'une exception soit levee par un Guard, un Pipe ou le Handler, le Filter l'attrape et formate une reponse d'erreur propre." }
  ]},
  { file: "quiz-03-03-auth-architecture.html", title: "Quiz — Architecture d'authentification", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "PKCE", text: "Pourquoi le flux Authorization Code + PKCE est-il prefere au flux Implicit pour les SPA ?", options: ["Il est plus simple a implementer", "Le flux Implicit expose le token dans l'URL et ne supporte pas les refresh tokens — PKCE est plus securise", "PKCE est plus rapide", "Le flux Implicit ne fonctionne plus dans les navigateurs modernes"], answer: 1, explanation: "Le flux Implicit met le token dans le fragment URL (visible dans l'historique, logs). PKCE echange le code via POST (jamais dans l'URL) et supporte les refresh tokens. Implicit est deprecie dans OAuth 2.1." },
    { label: "JWT validation", text: "Pourquoi valider un JWT avec RS256 et le JWKS endpoint plutot que HS256 et un secret partage ?", options: ["RS256 est plus rapide", "Avec RS256, le serveur verifie avec la cle publique sans jamais connaitre la cle privee — pas de secret partage a proteger", "HS256 ne fonctionne pas avec les navigateurs", "RS256 genere des tokens plus courts"], answer: 1, explanation: "RS256 utilise une paire cle privee/publique. Le serveur ne connait que la cle publique (JWKS) pour verifier. Avec HS256, le meme secret est partage entre emetteur et verificateur — plus risque." },
    { label: "RBAC", text: "Dans un systeme RBAC hierarchique, si un Admin herite du role Editor, quelles permissions a-t-il ?", options: ["Seulement les permissions Admin", "Toutes les permissions Admin ET toutes les permissions Editor", "Seulement les permissions Editor", "Aucune permission par defaut"], answer: 1, explanation: "La hierarchie RBAC signifie que Admin inclut toutes les permissions de Editor plus ses propres permissions. C'est un systeme additif : chaque niveau herite du precedent." },
    { label: "Stockage tokens", text: "Quelle est la meilleure approche pour stocker les tokens d'authentification cote client ?", options: ["localStorage car c'est simple", "Cookies HttpOnly + Secure + SameSite=Strict car ils sont inaccessibles au JavaScript", "sessionStorage car il est plus securise que localStorage", "Dans une variable globale JavaScript"], answer: 1, explanation: "Les cookies HttpOnly ne sont pas accessibles via document.cookie (protection XSS), Secure force HTTPS, SameSite=Strict empeche les envois cross-site (protection CSRF)." },
    { label: "Refresh token", text: "Pourquoi utilise-t-on un access token court (15min) et un refresh token long (7j) plutot qu'un seul token long ?", options: ["Pour economiser de la bande passante", "Si l'access token est compromis, la fenetre d'exploitation est limitee a 15 minutes", "Pour simplifier le code", "Parce que les JWT ne supportent pas les longs TTL"], answer: 1, explanation: "Un access token court limite les degats en cas de vol. Le refresh token (stocke en cookie HttpOnly) permet d'en obtenir un nouveau sans redemander le mot de passe." }
  ]},
  { file: "quiz-03-04-multi-tenancy.html", title: "Quiz — Multi-tenancy", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Strategies d'isolation", text: "Quels sont les 3 niveaux d'isolation dans une architecture multi-tenant ?", options: ["Frontend, Backend, Base de donnees", "Schema PostgreSQL, SQL Filters automatiques, Storage prefix S3", "Serveurs separes, Reseaux separes, DNS separes", "Authentification, Autorisation, Chiffrement"], answer: 1, explanation: "Les 3 couches sont independantes : schema PostgreSQL (SET search_path), filtres SQL automatiques (tenant_id), et prefixes S3 ({tenant}/{site}/media/). Meme si l'une echoue, les autres protegent." },
    { label: "Extraction du tenant", text: "Comment un tenant est-il typiquement identifie dans une requete entrante ?", options: ["Par l'adresse IP du client", "Par un claim dans le JWT (tenant_id) avec fallback sur un header HTTP X-Tenant-Id", "Par le nom de domaine uniquement", "Par un cookie de session"], answer: 1, explanation: "Le JWT claim est la source principale (fiable, signee). Le header X-Tenant-Id est un fallback. Le middleware rejette la requete si aucun tenant n'est identifie." },
    { label: "Schema per tenant", text: "Quel est l'avantage du schema-per-tenant par rapport a une colonne tenant_id dans chaque table ?", options: ["C'est plus rapide pour les lectures", "L'isolation est au niveau PostgreSQL — un bug ou un oubli de filtre ne peut pas fuiter les donnees d'un autre tenant", "C'est plus simple a implementer", "Ca consomme moins d'espace disque"], answer: 0, explanation: "Avec un schema par tenant, SET search_path garantit que les requetes ne voient que les donnees du bon tenant. Avec tenant_id, un oubli de filtre WHERE expose les donnees de tous les tenants." },
    { label: "Risque majeur", text: "Quel est le risque de securite majeur dans une application multi-tenant ?", options: ["La latence elevee", "Un tenant qui accede aux donnees d'un autre tenant par un defaut d'isolation", "La complexite du code", "Le cout des serveurs"], answer: 1, explanation: "La fuite de donnees inter-tenants est le risque numero un. Un oubli de filtre tenant_id, un bug de schema switching, ou un cache partage peut exposer les donnees sensibles d'un client a un autre." },
    { label: "Multi-site", text: "Quelle est la difference entre multi-tenancy et multi-site ?", options: ["Ce sont des synonymes", "Multi-tenancy = plusieurs organisations isolees, Multi-site = plusieurs sites web au sein d'un meme tenant", "Multi-site est plus securise", "Multi-tenancy est pour le cloud, multi-site pour on-premise"], answer: 1, explanation: "Un tenant (organisation) peut avoir plusieurs sites (site marketing, blog, boutique). L'isolation tenant empeche les fuites entre organisations. L'isolation site separe les contenus au sein d'un tenant." }
  ]},
  { file: "quiz-03-05-data-access-patterns.html", title: "Quiz — Data Access Patterns", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Unit of Work", text: "Quel est le role du pattern Unit of Work ?", options: ["Executer une seule requete SQL", "Regrouper toutes les modifications d'une transaction en une seule unite atomique — tout s'execute ou rien", "Optimiser les index de la base de donnees", "Generer les migrations automatiquement"], answer: 1, explanation: "Le Unit of Work suit toutes les entites modifiees pendant une transaction et les persiste en une seule operation atomique. Si une partie echoue, tout est annule (rollback)." },
    { label: "Content Versioning", text: "Pourquoi un rollback en content versioning est-il 'non destructif' ?", options: ["Parce qu'il ne modifie pas le fichier", "Parce que revenir a la v3 cree une nouvelle version (v11) avec le meme contenu — l'historique complet reste intact", "Parce qu'il utilise des sauvegardes", "Parce qu'il ne fonctionne qu'en lecture"], answer: 1, explanation: "On ne supprime jamais une version. 'Revenir a la v3' = creer une nouvelle version dont le contenu est identique a l'ancienne v3. L'historique reste intact pour l'auditabilite." },
    { label: "Active Record vs Data Mapper", text: "Pourquoi le Data Mapper est-il preferable pour une Clean Architecture ?", options: ["Il est plus rapide", "L'entite est un objet pur decouple de la DB, ce qui respecte la Dependency Rule", "Il genere moins de requetes", "Il est plus simple a configurer"], answer: 1, explanation: "Avec Active Record, l'entite connait la DB (product.save()). Avec Data Mapper, l'entite est pure — un mapper separe traduit entre entite et persistance. Le domaine reste isole." },
    { label: "Diff-based versioning", text: "Pourquoi stocker des diffs plutot que des copies completes pour le versioning de contenu ?", options: ["Les diffs sont plus lisibles", "Les diffs economisent enormement d'espace quand seuls quelques champs changent entre versions", "Les diffs sont plus rapides a appliquer", "C'est obligatoire avec PostgreSQL"], answer: 1, explanation: "Si un article de 10 000 caracteres change 1 mot, stocker une copie complete gaspille 99.99% d'espace. Le diff ne stocke que le changement, avec un ratio de compression bien meilleur." },
    { label: "Presigned URL upload", text: "Quelle est l'etape finale du flux d'upload via presigned URL ?", options: ["Le client envoie le fichier au serveur API", "Le client appelle POST /media/:id/confirm pour que le serveur verifie l'existence du fichier sur S3", "Le serveur telecharge le fichier depuis S3", "Le client notifie directement S3"], answer: 1, explanation: "Apres l'upload direct vers S3, le client appelle confirm. Le serveur verifie que le fichier existe bien sur S3, met a jour le statut de pending a confirmed. Le serveur n'a jamais touche le binaire." }
  ]},
  { file: "quiz-03-06-validation-error-handling.html", title: "Quiz — Validation et Error Handling", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "3 couches de validation", text: "Quelles sont les 3 couches de validation dans une API bien structuree ?", options: ["Frontend, Backend, Base de donnees", "DTO validation (format), Domain validation (regles metier), Persistence validation (contraintes DB)", "Syntaxique, Semantique, Pragmatique", "Input, Process, Output"], answer: 1, explanation: "On valide du plus generique au plus specifique : DTO (format, presence), Domain (invariants metier), Persistence (unique, FK, check). Chaque couche rejette au plus tot." },
    { label: "RFC 7807", text: "Quels champs sont standard dans une reponse RFC 7807 Problem Details ?", options: ["error, message, code", "type (URI), title, status, detail, instance", "statusCode, errorName, stackTrace", "code, description, timestamp"], answer: 1, explanation: "RFC 7807 definit type (URI du type d'erreur), title (description humaine), status (code HTTP), detail (description specifique), instance (URI de la ressource). Extensible avec des champs custom." },
    { label: "Validation DTO vs Domain", text: "Quelle validation appartient au DTO et laquelle au Domain ?", options: ["Le DTO verifie les regles metier, le Domain verifie le format", "Le DTO verifie le format (email valide, champ requis), le Domain verifie les invariants metier (article doit etre en Draft pour etre publie)", "Les deux font la meme chose", "Seul le Domain valide"], answer: 1, explanation: "Le DTO est le 'controle des documents' (format correct). Le Domain est le 'controle de securite' (regles metier). Separer permet de rejeter les erreurs de format avant d'atteindre la logique metier." },
    { label: "Code HTTP semantique", text: "Pourquoi retourner HTTP 200 avec un champ 'error' dans le body est-il un anti-pattern ?", options: ["Parce que 200 est reserve aux GET", "Parce que les proxies, load balancers et outils de monitoring utilisent le code HTTP — un 200 avec erreur trompe toute l'infrastructure", "Parce que le body est trop volumineux", "Parce que les navigateurs ne lisent pas le body"], answer: 1, explanation: "Les retry policies, le monitoring, les load balancers — tous se basent sur le code HTTP. Un 200 avec erreur dans le body force chaque client a implementer sa propre detection d'erreur." },
    { label: "Guard clauses", text: "Dans quel ordre valider les preconditions d'une fonction avec des guard clauses ?", options: ["Du plus specifique au plus generique", "Du plus generique au plus specifique — rejeter les cas triviaux d'abord", "Dans l'ordre alphabetique", "L'ordre n'a pas d'importance"], answer: 1, explanation: "On verifie d'abord les cas les plus simples (null, vide) puis les regles metier plus complexes. Chaque guard clause est un return/throw precoce qui evite le deep nesting." }
  ]},
  { file: "quiz-03-07-background-jobs-queues.html", title: "Quiz — Background Jobs et Queues", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Pourquoi asynchrone", text: "Pourquoi deporter l'envoi d'email dans un background job plutot que le faire dans la requete HTTP ?", options: ["Pour que l'email soit plus joli", "Pour que la requete HTTP reponde rapidement sans attendre le serveur SMTP — et pour pouvoir retenter en cas d'echec", "Pour economiser de la bande passante", "Pour eviter les spams"], answer: 1, explanation: "Un envoi SMTP peut prendre 2-5 secondes. Le deporter dans un job permet de repondre immediatement au client (202 Accepted) et de gerer les echecs avec des retries automatiques." },
    { label: "Idempotence des jobs", text: "Pourquoi un background job doit-il etre idempotent ?", options: ["Pour des raisons de performance", "Parce qu'un job peut etre execute plusieurs fois (retry apres echec) et doit produire le meme resultat", "Pour simplifier le code", "Parce que BullMQ l'exige"], answer: 1, explanation: "Un worker peut crasher apres avoir traite un job mais avant d'avoir envoye l'ACK. Le job sera re-execute. Sans idempotence, on risque un double debit, un double email, etc." },
    { label: "Dead Letter Queue", text: "Qu'est-ce qu'une Dead Letter Queue et pourquoi ne faut-il pas l'ignorer ?", options: ["Une queue pour les messages de test", "La queue ou atterrissent les jobs qui ont echoue apres le nombre maximal de retries — chaque job represente un bug ou un systeme en panne", "Une queue de priorite basse", "Une queue temporaire pour les pics de charge"], answer: 1, explanation: "Chaque job en DLQ est un probleme non resolu : bug dans le code, systeme externe en panne, donnees corrompues. Ignorer la DLQ = ignorer des erreurs silencieuses en production." },
    { label: "Retry strategy", text: "Pourquoi utiliser un backoff exponentiel pour les retries plutot qu'un intervalle fixe ?", options: ["C'est plus simple a configurer", "Pour eviter de marteler un service deja en difficulte — les intervalles croissants lui laissent le temps de recuperer", "Pour economiser de la memoire", "Pour respecter les standards HTTP"], answer: 1, explanation: "Si un service est down, le retry a intervalle fixe (1s, 1s, 1s) le surcharge davantage. Le backoff exponentiel (1s, 2s, 4s, 8s) donne de plus en plus de temps pour la recuperation." },
    { label: "Recurring tasks", text: "Comment garantir qu'un job CRON (ex: nettoyage quotidien) ne s'execute pas en doublon sur un cluster de 3 workers ?", options: ["En deployant un seul worker", "En utilisant un lock distribue (Redis SETNX) — le premier worker qui acquiert le lock execute, les autres passent", "En utilisant des timestamps", "En configurant un worker par job"], answer: 1, explanation: "Sur un cluster, 3 workers voient le meme CRON. Un lock distribue (Redis SETNX avec TTL) garantit qu'un seul worker execute le job. Les autres detectent le lock et passent." }
  ]},
  { file: "quiz-03-08-concurrence-asynchronisme.html", title: "Quiz — Concurrence et Asynchronisme", subtitle: "Module 03 — Architecture Backend", questions: [
    { label: "Event loop Node.js", text: "Comment Node.js gere-t-il des milliers de connexions simultanees avec un seul thread ?", options: ["Il cree un thread par connexion", "Il utilise des I/O non-bloquantes : pendant qu'il attend la DB, il traite d'autres requetes", "Il limite le nombre de connexions", "Il utilise du multi-processing automatique"], answer: 1, explanation: "Node.js delegue les I/O au systeme (libuv). Pendant qu'une requete attend la DB, le thread traite d'autres requetes. Comme un serveur de restaurant rapide qui prend les commandes sans attendre la cuisine." },
    { label: "Lock optimiste vs pessimiste", text: "Quand utiliser un lock pessimiste (SELECT FOR UPDATE) plutot qu'un lock optimiste (version) ?", options: ["Toujours, le pessimiste est plus sur", "Quand les conflits sont frequents et la coherence critique (ex: debit de solde, reservation de stock)", "Quand la base est petite", "Jamais, le pessimiste est un anti-pattern"], answer: 1, explanation: "Le lock optimiste convient quand les conflits sont rares (edition CMS). Le pessimiste bloque la ligne — necessaire quand les conflits sont frequents (stock, paiement) et qu'on ne peut pas se permettre de rejeter." },
    { label: "Isolation levels", text: "Quel probleme le niveau d'isolation Serializable resout-il par rapport a Read Committed ?", options: ["Il est plus rapide", "Il empeche les anomalies de serialisation (phantom reads, write skew) mais au prix de performances reduites", "Il consomme moins de memoire", "Il est le niveau par defaut de PostgreSQL"], answer: 1, explanation: "Serializable garantit que les transactions concurrentes produisent le meme resultat que si elles s'executaient une par une. C'est le plus sur mais le plus lent — a utiliser pour les operations critiques." },
    { label: "Race condition", text: "Deux requetes lisent un stock de 1, puis chacune le decremente. Sans protection, quel est le resultat ?", options: ["Stock = -1 (une vente de trop)", "Stock = 0 (correct)", "Stock = 1 (aucun changement)", "Erreur de base de donnees"], answer: 0, explanation: "C'est une race condition classique : les deux lisent stock=1, les deux ecrivent stock=0. Un article est vendu deux fois. La solution : lock pessimiste ou UPDATE ... WHERE stock > 0 atomique." },
    { label: "Worker threads", text: "Quand utiliser des Worker Threads en Node.js plutot que l'event loop classique ?", options: ["Pour toutes les requetes HTTP", "Pour les operations CPU-intensives (compression, calcul, parsing lourd) qui bloqueraient l'event loop", "Pour les requetes a la base de donnees", "Pour l'envoi d'emails"], answer: 1, explanation: "L'event loop est optimal pour les I/O (DB, reseau). Les Worker Threads sont necessaires pour le CPU-bound (compression d'image, calcul cryptographique) qui bloquerait l'event loop et paralyserait le serveur." }
  ]},
];

// Generate all quiz files
let count = 0;
for (const quiz of quizzes) {
  const html = template(quiz.title, quiz.subtitle, quiz.questions);
  fs.writeFileSync(path.join(dir, quiz.file), html, 'utf8');
  count++;
}
console.log(`Generated ${count} quiz files in batch 1.`);
